#pragma once

/// Convenience header — includes all public headers.

#include "converter.hpp"
#include "ctrmml.hpp"
#include "dat.hpp"
#include "dmf.hpp"
#include "dmp.hpp"
#include "eif.hpp"
#include "format.hpp"
#include "fui.hpp"
#include "fur.hpp"
#include "gin.hpp"
#include "ginpkg.hpp"
#include "ins.hpp"
#include "opm.hpp"
#include "patch.hpp"
#include "result.hpp"
#include "rym2612.hpp"
#include "spat.hpp"
#include "tfi.hpp"
#include "tyi.hpp"
#include "vgi.hpp"
#include "vgm.hpp"
#include "y12.hpp"
